package: schwooops
version: '0.0.1-dev-2024-08-25'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/schwooops


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.16
    packages:
        maintenance: "^3"



page:
    title: translate:blaupause_title
    prio: 100
    icon: rex-icon fa-gear
    hidden: true

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
