package: schwooops
version: '0.0.1-dev-2024-08-25'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/schwooops


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.16
    packages:
        maintenance: "^3"



page:
    title: translate:schwooops_title
    icon: rex-icon fa-bug
    prio: 100
    hidden: true


pages:
    system/schwooops:
        title: translate:schwooops_title
        icon: rex-icon fa-bug
    maintenance/schwooops:
        title: translate:schwooops_title
        icon: rex-icon fa-bug

default_config:
    name: ''
    email: ''
    phone: ''
    contact: ''
    more: ''

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
